version: "3.3"

services:
  mysql-mozart-portal-db:
    image: mysql:8.0.33
    container_name: mysql-mozart-portal-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mozart_q_submissions
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 49760:3306
    volumes:
      - /etc/localtime:/etc/localtime
      - mozartPortalDb:/var/lib/mysql
    restart: unless-stopped

  mozart-backend-service:
    image: eclipse-temurin:17-jdk-alpine
    container_name: mozart-backend-service
    ports:
      - 8085:8085
    working_dir: /home/mozart
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime
    restart: unless-stopped

  app:
    container_name: mozart-portal
    image: mozart-portal-image
    volumes:
      - /etc/localtime:/etc/localtime
    build: 
      context: .
    ports:
      - 8181:3000
    depends_on:
      - mysql-mozart-portal-db
    restart: unless-stopped  

volumes:
  mozartPortalDb:
    external: true